# Generated by Django 5.2.14 on 2026-05-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0012_visual_tutor_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='evidence_guidance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='expected_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('short_answer', 'Short answer')], default='multiple_choice', max_length=32),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='correct_option',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option_a',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option_b',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option_c',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option_d',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
