# Generated by Django 5.2.14 on 2026-05-24 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_adminauditlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adminauditlog',
            new_name='core_admina_action_09f2d5_idx',
            old_name='core_admin_action_992083_idx',
        ),
        migrations.RenameIndex(
            model_name='adminauditlog',
            new_name='core_admina_target__1d4d61_idx',
            old_name='core_admin_target__3d42b4_idx',
        ),
    ]
